<?php

namespace CCICommunity\BaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VDCRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VDCRepository extends EntityRepository
{
}
