<?php

namespace CCICommunity\ConseilBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdressesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdressesRepository extends EntityRepository
{
}
