<?php

namespace CCICommunity\ConseilBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * AdressesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdressesRepository extends EntityRepository
{

    public function getList($page=1, $maxperpage=6)
    {

      $q = $this->createQueryBuilder('v');
      $q->orderBy('v.date', 'DESC');
	     
	    $q->setFirstResult(($page-1) * $maxperpage)
	    ->setMaxResults($maxperpage);
	    return new Paginator($q);
    }

    public function countTotalAdresses ()
    {

     $query = $this->createQueryBuilder('Adresses')->select('COUNT(Adresses)');
     $total = $query->getQuery()->getSingleScalarResult();
     return $total;
   }
}
