parameters:
#    cci_community_conseil.example.class: CCICommunity\ConseilBundle\Example

services:
#    cci_community_conseil.example:
#        class: %cci_community_conseil.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
