parameters:
#    cci_community_base.example.class: CCICommunity\BaseBundle\Example

services:
#    cci_community_base.example:
#        class: %cci_community_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
