parameters:
#    cci_community_annonces.example.class: CCICommunity\AnnoncesBundle\Example

services:
#    cci_community_annonces.example:
#        class: %cci_community_annonces.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
